# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=Pranjal2607!@
ENV MYSQL_DATABASE=employees_db

# Expose the default MySQL port
EXPOSE 3306

